# Generated by Django 4.2.6 on 2023-10-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(),
        ),
    ]
